name: Update instadapp API Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:      # Permet de le lancer manuellement pour tester

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch and Append Data
        run: |
          # 1. GET APY from API
          API_RES=$(curl -s "https://api.instadapp.io/v2/mainnet/lite/users/0x56e001745f105e34afe45398d7bc366db8fc5792/vaults" | jq '.[0].apy')
          
          NET_APY=$(echo $API_RES | jq '.apyWithFee | tonumber')
          GROSS_APY=$(echo $API_RES | jq '.apyWithoutFee | tonumber')
          
          # 2. Création de la nouvelle entrée avec Date, APY avec frais et APY sans frais
          NEW_ENTRY=$(jq -n \
            --arg date "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --arg net_apy "$NET_APY" \
            --arg gross_apy "$GROSS_APY" \
            '{date: $date, net_apy: ($net_apy | tonumber), gross_apy: ($gross_apy | tonumber)}')

          # 3. Initialisation du fichier si inexistant
          if [ ! -f data.json ]; then echo "[]" > data.json; fi

          # 4. Ajout au tableau historique
          cat data.json | jq ". += [$NEW_ENTRY]" > temp.json && mv temp.json data.json

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Auto-update data: $(date)" || exit 0
          git push
